
["Config for Genie Lamp"]
	#List of banned items that will not be able to wish
	"Blocked items" = ["minecraft:reinforced_deepslate", "minecraft:dragon_egg", "minecraft:end_portal_frame", "minecraft:bedrock", "minecraft:command_block", "minecraft:chain_command_block", "minecraft:repeating_command_block", "minecraft:command_block_minecart", "minecraft:jigsaw", "minecraft:structure_block", "minecraft:structure_void", "minecraft:debug_stick", "minecraft:light", "minecraft:barrier"]
	#Amount of XP levels required to charge lamp
	"XP amount" = 100

